version: '2'
services:
  clamav-svc:
    environment: 
      - HMAC_KEY=<Enter your key here>
      - ROLES_DYNAMOTABLE=clamavroles
    image: clamav/clamav-svc
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ~/.aws/:/root/.aws:ro